services:
  parser-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: parser_app:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      parser-database:
        condition: service_healthy
    restart: always

  parser-backend-migrations:
    image: parser_app:latest
    env_file:
      - .env.docker
    command: >-
      bash -c "alembic upgrade head"
    depends_on:
      parser-database:
        condition: service_healthy
      parser-backend:
        condition: service_started
    restart: "no"

  parser-database:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wikiparser_db
    volumes:
      - parser-database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]
    restart: always


volumes:
  parser-database-data: